[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.build]
cmds = ["cd frontend && npm install && npm run build", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
